import requests
import uuid

BASE_URL = "http://localhost:3001"
TIMEOUT = 30

ADMIN_CREDENTIALS = {"username": "renshu", "password": "renshu123"}
DEMO_CREDENTIALS = {"username": "gabby_demo", "password": "gabby123"}
GUEST_TOKEN = None  # No token for guest (unauthorized)

VALID_TYPES = [
    "shortcuts",
    "groups",
    "apps",
    "leaderShortcuts",
    "raycastShortcuts",
    "systemShortcuts",
    "leaderGroups",
    "raycastGroups",
    "systemGroups"
]

INVALID_TYPE = "invalidTypeTest"

HEADERS = {"Content-Type": "application/json"}


def login_get_token(username, password):
    try:
        resp = requests.post(
            f"{BASE_URL}/api/auth/login",
            json={"username": username, "password": password},
            timeout=TIMEOUT,
        )
        resp.raise_for_status()
        return resp.json().get("token")
    except Exception:
        return None


def create_resource(token, type_, data):
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    response = requests.post(
        f"{BASE_URL}/api/shortcuts/{type_}",
        headers=headers,
        json=data,
        timeout=TIMEOUT,
    )
    response.raise_for_status()
    return response.json()


def delete_resource(token, type_, id_):
    headers = {"Authorization": f"Bearer {token}"}
    response = requests.delete(
        f"{BASE_URL}/api/shortcuts/{type_}/{id_}", headers=headers, timeout=TIMEOUT
    )
    return response


def test_tc008_delete_shortcut_group_app_authorization():
    # Login tokens for admin and demo users
    admin_token = login_get_token(**ADMIN_CREDENTIALS)
    demo_token = login_get_token(**DEMO_CREDENTIALS)

    assert admin_token is not None, "Admin login failed"
    assert demo_token is not None, "Demo login failed"

    # Prepare a new item data for creation (choosing 'groups' as a type example)
    type_ = "groups"
    created_id = None
    created_by_demo_id = None

    # Sample valid group data without id (id auto-generated by server)
    group_data = {
        "name": f"Test Group {uuid.uuid4()}",
        "icon": "test-icon",
        "color": "#abcdef",
    }

    # Create resource with admin token
    try:
        # Create with admin
        create_resp = create_resource(admin_token, type_, group_data)
        # The API doc for create returns 200 with created item (no specific schema)
        # Expect an 'id' in response or something similar; otherwise fallback to GET after creation
        created_id = create_resp.get("id")
        assert created_id is not None, "Failed to get created id for admin-created item"

        # Create resource with demo token
        create_resp_demo = create_resource(demo_token, type_, group_data)
        created_by_demo_id = create_resp_demo.get("id")
        assert created_by_demo_id is not None, "Failed to get created id for demo-created item"

        # --- TEST: Admin user can delete the created item ---
        resp = delete_resource(admin_token, type_, created_id)
        assert resp.status_code == 200
        resp_json = resp.json()
        assert "success" in resp_json and resp_json["success"] is True

        # --- TEST: Demo user can delete the created item ---
        resp_demo = delete_resource(demo_token, type_, created_by_demo_id)
        assert resp_demo.status_code == 200
        resp_demo_json = resp_demo.json()
        assert "success" in resp_demo_json and resp_demo_json["success"] is True

        # --- TEST: Guest (no auth) attempts to delete an item (should get 401 or 403) ---
        # First recreate the resource for guest attempt
        recreate_resp = create_resource(admin_token, type_, group_data)
        temp_id = recreate_resp.get("id")
        assert temp_id is not None

        resp_guest = requests.delete(
            f"{BASE_URL}/api/shortcuts/{type_}/{temp_id}", timeout=TIMEOUT
        )
        # API may return 401 for no auth or 403 for unauthorized; accept either
        assert resp_guest.status_code in (401, 403), f"Expected 401 or 403 for guest, got {resp_guest.status_code}"

        # Cleanup: Delete the resource by admin
        resp_clean = delete_resource(admin_token, type_, temp_id)
        assert resp_clean.status_code == 200
        resp_clean_json = resp_clean.json()
        assert resp_clean_json.get("success") is True

        # --- TEST: Invalid type parameter returns 400 ---
        # Use admin token for auth
        resp_invalid_type = delete_resource(admin_token, INVALID_TYPE, "some-id")
        assert resp_invalid_type.status_code == 400

    finally:
        # Cleanup any leftovers in case deletes failed above
        headers_admin = {"Authorization": f"Bearer {admin_token}"}
        if created_id is not None:
            requests.delete(
                f"{BASE_URL}/api/shortcuts/{type_}/{created_id}",
                headers=headers_admin,
                timeout=TIMEOUT,
            )
        if created_by_demo_id is not None:
            headers_demo = {"Authorization": f"Bearer {demo_token}"}
            requests.delete(
                f"{BASE_URL}/api/shortcuts/{type_}/{created_by_demo_id}",
                headers=headers_demo,
                timeout=TIMEOUT,
            )


test_tc008_delete_shortcut_group_app_authorization()